### ISSUE TITLE
Install Linux

### ISSUE THREAD

**Issue by gomezgleonardob** [aethyx/ps3linux#1]
**Install Other OS**

- It is possible to change the cfw from ps3 to 3.15, to install other os, currently I have cech 2001a with cfw charges 4.82, thanks for the reply

**Comment by kabone** [comment]
Why do you want to go to 3.15 with a 2001a? What's the min version it's been on?

**Comment by ghost** [comment]
Even if minCheckVersion give you 3.15 on a slim, you won’t have opportunity to install Linux on it.


If you want to install linux on slim, you will have to use a OtherOS++ enabled CFW.

**Some Details:**
Those patched CFW will reformat the HDD to make some space for linux. You can grab one already patched or create your own with MFWbuilder.

Once done, you will need a petitboot build with patched kernel to run on otheros++, again you can grab one (ex:  [dtbImage.ps3.bin](https://github.com/Tcherenkov/PS3-OtherOS/raw/master/dtbImage.ps3.bin) for the ps3 slim (NOR flash) or [dtbImage.ps3.bin.minimal
](https://github.com/Tcherenkov/PS3-OtherOS/raw/master/dtbImage.ps3.bin.minimal) for old Ps3 Phat with Nand flash) or build one.

Once you have all those elements, you can proceed to the actual installation. 

1) Install your otheros++ patched CFW. (reinstall in recovery mode to format HDD)
2) Flash petitboot with a package like the one in [rebug's toolbox](https://rebug.me/rebug-toolbox/).
3) Boot petitboot. Can be done with rebug's toolbox
4) reformat the newly created partition with something like [this](https://raw.githubusercontent.com/Tcherenkov/PS3-OtherOS/master/create_hdd_region.sh).
5) Install linux.
               Simple outdated : [RRL](https://sourceforge.net/projects/redribbon/)
               Up to date SDE  : [T2 SDE](https://www.youtube.com/watch?v=xrCppgWK3AQ)
               Build your own using chroot ([debootsrap](https://www.psdevwiki.com/ps3/OtherOS%2B%2B#Debian), ...)




[Edit]: Added some details on how to install linux via otheros++

**Comment by gomezgleonardob** [comment]
Thanks for Response,it's impossible :/

**Comment by kabone** [comment]
That's not totally  true. I have run on all models 2501a and under. **You cannot downgrade to 3.15** but you can definitely boot/install a bootloader and linux.. Check out rebug toolbox and petitboot for the ps3 slim. If you have issues don't be afraid to ask. I was told the same thing, I didn't take that as an answer, it was surprisingly simple to do.. 


Some links to look at for simple solutions:
http://www.psx-place.com/threads/tutorial-installing-red-ribbon-linux-on-rebug-4-81-2-d-rex.16419/
http://jk.ozlabs.org/projects/petitboot/
http://redribbongnulinux.000webhostapp.com/ Red Ribbon a ps3 distro based Debian Jessie. Has support for the CELL SDK 3.1 and works with all files in this repo..

**Comment by Tcherenkov** [comment]
The question was about installing Linux via 3.15 OFW otheros.

This feature isn’t available on slim.

If you want to install Linux via otheros++ there’s a lot of possibilities. (Chroot to get an updated install of Debian, gentoo... compile a new distro like T2 SDE ( working on RSX driver ), etc).

The petitboot link you posted won’t work with otheros++ ( not patched to do so).

For the record, we can kexec up to date Linux kernel, RRL is outdated.

**Comment by gomezgleonardob** [comment]
I followed this tutorial in the Spanish 

[Red Ribbon Spanish](https://www.elotrolado.net/hilo_red-ribbon-gnu-linux-para-ps3-23-03-2016_1631472)


Thanks ,I will review the links posted

**Comment by c1ph4** [comment]
We moved: https://gitlab.com/aethyx/ps3linux
Please leave comments/issues/likes/forks/etc. there.
Closing this now.
