### ISSUE TITLE
tried to compile 

### ISSUE THREAD

**Issue by DevX-Cipher** [aethyx/ps3linux#2]
hi i tried to compile these and they dont compiles some of the files are missing 

this is for encdec.c 

encdec.c:59:27: error: ‘AES_BLOCK_SIZE’ undeclared here (not in a function); did you mean ‘S_BLKSIZE’?
 static unsigned char rnd1[AES_BLOCK_SIZE];
                           ^~~~~~~~~~~~~~

**Comment by modz2014** [comment]
ok i fix the issues but i get this 

modz2014@DESKTOP-MJJP3OM:~/ps3linux-encdec$ sudo make
gcc -lcrypto -lssl -o encdec encdec.o
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'encdec' failed
make: *** [encdec] Error 1
modz2014@DESKTOP-MJJP3OM:~/ps3linux-encdec$
